#Change to MySQL for mysql support#
#Change to SQLite for sqlite support#
Database: SQLite
mysql-database: 'jdbc:mysql://localhost:3306/minecraft'
mysql-user: 'root'
mysql-password: 'root'
#Change these if you want to load or create different databases#
#First load will create these databases#
mysql-table: banlist
mysql-table-ip: banlistip
#SQLite Information#
sqlite-dbname: banlist
#parameters#
auto-complete: true
#Command Checks#
useFine: true
#Max allowable fine#
maxFineAmt: 0
useJail: true
useLockdown: true
useStarve: true
useForceRespawn: true
useEmpty: true
usePermaban: true
useWarn: true
useRules: true
#Default labels#
defAdminName: 'server'
defReason: 'not sure'
#change to true or false to enable lockdown#
#also can be done ingame /lockdown#
lockdown: false
dupePolicy: false
messages:
  banMsgFailed: '&c%victim% &8is already banned!'
  unbanMsg: '&8Successfully unbanned &c%victim%&8!'
  unbanMsgBroadcast: '&c%victim% &8was unbanned by &9%admin%&8!'
  unbanMsgFailed: '&c%victim% &8is already unbanned!'
  kickAllMsg: '%admin% kicked everyone. Reason: %reason%!'
  kickMsgVictim: 'You have been kicked by %admin%. Reason: %reason%!'
  kickMsgBroadcast: '&c%victim% &8was kicked by &9%admin%&8. Reason: &c%reason%!'
  kickMsgFailed: '&8Kick failed: &8%victim% &8isn''t online.'
  banMsgVictim: 'You have been banned by %admin%. Reason: %reason%!'
  banMsgBroadcast: '&c%victim% &8was banned by &9%admin%&8. Reason: &c%reason%!'
  permbanMsgVictim: 'You have been permabanned by %admin%. Reason: %reason%!'
  permbanMsgBroadcast: '&c%victim% &8has been permabanned by &9%admin%&8. Reason: &c%reason%!'
  tempbanMsgVictim: 'You have been temp. banned by %admin%. Reason: %reason%!'
  tempbanMsgBroadcast: '&c%victim% &8was temp. banned by &9%admin%&8. Reason: &c%reason%!'
  LoginTempban: '&8You are banned until &c%time%&8! Reason: &c%reason%!'
  LoginBan: '&8You are banned from this server! Reason: &c%reason%!'
  LoginIPBan: 'Your IP is banned!'
  fineMsgVictim: 'You have been fined by %admin% in the amount of %amt%!'
  fineMsgBroadcast: '&c%victim% &8was fined by &9%admin%&8 in the amount of &c%amt%!'
  emptyMsgVictim: '&9%admin% has cleared your inventory!'
  emptyMsgBroadcast: '&9%admin% has cleared the inventory of &c%victim%!'
  starveMsgVictim: '&8You are now starving!'
  starveMsgBroadcast: '&c%victim% is now starving!'
  fspawnMsgVictim: '&8You have been sent to spawn!'
  fspawnMsgBroadcast: '&c%victim% &8is now at spawn!'
  jailMsgVictim: '&8You have been jailed by &9%admin%&8. Reason: &c%reason%!'
  jailMsgRelease: '&c%victim% &8was released from jail by &9%admin%&8!'
  jailMsgBroadcast: '&c%victim% &8was jailed by &9%admin%&8. Reason: &c%reason%!'
  warnMsgVictim: '&8You have been warned by &9%admin%&8. Reason: &c%reason%!'
  warnMsgBroadcast: '&c%victim% &8was warned by &9%admin%&8. Reason: &c%reason%!'
  lockMsgLogin: 'Server is under a lockdown, Try again later! Sorry.'
  DupeIPKick: 'Duplicate IP addresses disabled.'
  jailCmdMsg: 'You cannot use commands while jailed!'
  jailChatMsg: 'Your cry falls on deaf ears.'
  jailPlaceMsg: 'You cannot place blocks while you are jailed!'
  jailBreakMsg: 'You cannot break blocks while you are jailed!'
  muteChatMsg: 'You have been muted!'
  unmuteMsgVictim: 'You have been unmuted.'
  unmuteMsg: 'You have unmuted %victim%.'
  
  ruleMsg: '&9The Servers Rules Are As Follows!'
#Adjust as you see fit or set ingame.#
rules:
  one:
  two:
  three:
  four:
  five:
  six:
  seven:
  eight:
  nine:
  ten:
#Do Not Change Values Below#
jail:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
