#Other Databases are not available... yet#
mysql: true
mysql-database: 'jdbc:mysql://localhost:3306/minecraft'
mysql-user: 'root'
mysql-password: 'root'
#Change these if you want to load a database#
#First load will create these databases#
mysql-table: banlist
mysql-table-ip: banlistip
#Disable this if you do not want to use the -s#
#to silence broadcastss#
auto-complete: true
#Ultraban requires Vault for the Command /fines#
#Disable this is you don't not want to use /fines#
#Or would rather not use the Vault Library#
useFine: true
#Bukkit depreciated the standard config#
#Custom commands and messages are soone to come#