#Change to MySQL for mysql support#
#Change to SQLite for sqlite support#
Database: SQLite
#MySQL Information#
MySQL:
  Database: 'jdbc:mysql://localhost:3306/minecraft'
  User: 'root'
  Password: 'root'
  Table: 'banlist'
  IPTable: 'banlistip'
#SQLite Information#
SQLite:
  Filename: 'banlist'
#delete dat on ban#
CleanOnBan: true
#clear warnings on ban#
ClearWarnOnBan: false
Log:
  Enabled: true
#Max Warnings#
MaxWarning:
  Enable: false
  Amt: 5
  #ban,kick,ipban,perma,tempban,tempipban#
  Result: ban
  Silent: true
  Reason: 'Max Warnings'
  #Used with Temporary actions#
  Temp:
    Amt: 5
  #sec,min,hour,day,week,month#
    Mode: day
#Default labels#
Label:
  Console: 'Server'
  Reason: 'Unsure'
#change to true or false to enable lockdown#
#also can be done ingame /lockdown#
Lockdown: false
Login:
#Check for duplicates on Login#
  DupeCheck:
    Enable: true
#Auto Updater#
AutoUpdater:
  Enabled: true
#Chat#
Chat:
  #Checks Chat Messages for a valid IP address#
  #If its not valid, trust me they can't connect to it#
  IPCheck:
    Enable: true
    #Wildcards %scramble% will scramble the ip and %replace% will show your ip instead#
    #If no wildcards are present the message entered will replace the ip#
    #leave blank to erase#
    Blocking: '{Block}'
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: warn
    Silent: false
    Reason: 'Advertising'
  #This will allow you to filter out messages containing any words that you define#
  SwearCensor:
    Enable: true
    #Use your imagination these are not for me to decide#
    Words: 'test testing tests'
    #Wildcards %scramble% will scramble the word#
    #If no wildcards are present the message entered will replace the word#
    #leave blank to erase#
    Blocking: '{Block}'
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: warn
    Silent: false
    Reason: 'Language'
  #Checks if the message is duplicate and disables it#
  SpamCheck:
    Enable: true
    #The amount of messages to give a result#
    Counter: 10
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: kick
    Silent: false
    Reason: 'Spam'
Muted:
  Vannila: true
  #When Vanilla: true allowed commands.#
  AllowedCommands:
  - '/login'
  - '/register'
#Jail Configuration#
Jail:
  Mute: true
  Vanilla: true
  #When Vanilla: true allowed commands.#
  AllowedCommands:
  - '/login'
  - '/register'
Messages:
  TempIpBan:
    MsgToVictim: '&6You have been tempipbanned by &7%admin%&6 for &7%amt% %mode%s.&6 Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was tempipbanned by &7%admin%&6 for &7%amt% %mode%s.&6 Reason: &7%reason%&6!'
    Failed: '&4%victim%&c is already tempipbanned!'
    Denied: '&cYour tempipban has been denied!'
    Emo: '&cYou cannot tempipban yourself!'
    IPNotFound: '&cIP address not found.&6 Processed as a normal tempban for &7%victim%&6!'
  TempJail:
    MsgToVictim: '&6You have been tempjailed by &7%admin%&6 for &7%amt% %mode%s.&6 Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was tempjailed by &7%admin%&6 for &7%amt% %mode%s.&6 Reason: &7%reason%&6!'
    Failed: '&4%victim%&c is already jailed!'
    Denied: '&cYour tempjail has been denied!'
    Emo: '&cYou cannot tempjail yourself!'
  Unban:
    MsgToBroadcast: '&7%victim%&6 was unbanned by &7%admin%&6!'
    PermaBanned: '&cUnable to unban, &7%victim%&c was Permabanned.'
    Failed: '&4%victim%&c is already unbanned!'
  Warn:
    MsgToVictim: '&6You have been warned by &7%admin%&6. Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was warned by &7%admin%&6. Reason: &7%reason%&6!'
    Denied: '&cYour warning has been denied!'
    Emo: '&cYou cannot warn yourself!'
  MaxWarn:
    MsgToBroadcast: '&7%cmd%&6 performed by Ultrabans on &7%victim%&6. Reason: &7Reached Max Warnings&6!'
  Permission: 'You do not have the required permissions.'
Mode:
  Second: Second
  Minute: Minute
  Hour: Hour
  Day: Day
  Week: Week
  Month: Month
  Year: Year
