name: UltraBan
main: com.modcrafting.ultrabans.UltraBan
version: 0.2.4
website: http://modcrafting.com
author: Deathmarine
description: >
             Administration Plugin for Bukkit.
commands:
  kick:
    description: Kick a player
    usage: /<command> player [reason] - Kick a player
  tempban:
    description: Temporarily ban a player
    usage: /<command> player time timeform [reason] - Temporarily ban a player
  tempipban:
    description: Temporarily ipban a player
    usage: /<command> player time timeform [reason] - Temporarily ipban a player
  ban:
    description: Ban a player
    usage: /<command> player [reason] - Ban a player
  unban:
    description: Unban a player
    usage: /<command> player - Unban a player
  checkban:
    description: Check if a player is banned
    usage: /<command> player
  checkip:
    description: Check a players ip
    usage: /<command> player
  dupeip:
    description: Check a players ip against all players
    usage: /<command> player
  permaban:
    description: Unbannable Banning
    usage: /<command> player [reason] - Permaban
  ureload:
    description: Reload the banlist
    usage: /<command>
  ipban:
    description: IP-ban a player
    usage: /<command> player [reason]
  exportbans:
    description: Export bans to banned-players.txt
    usage: /<command>
  importbans:
    description: import bans from banned-players.txt and banned-ips.txt
    usage: /<command>
  history:
    description: shows recent entries
    usage: /<command>
  warn:
    description: Warn a player
    usage: /<command> player [reason] - Warn a player
  fine:
    description: Fine a player
    usage: /<command> player [amt] - Fine a player
  empty:
    description: Empty player inventory.
    usage: /<command> player - Empty a players inventory
  forcespawn:
    description: Sends player to spawn/home
    usage: /<command> player - Sends player to spawn/home
  starve:
    description: Removes food from player
    usage: /<command> player - Removes food from player
  jail:
    description: Jail player
    usage: /<command> <set/pardon/player> player - pardon player
  tempjail:
    description: Temporary Jail Player
    usage: /<command> player time timeform [reason]
  umute:
    description: Mute player
    usage: /<command> <player> player - mutes / unmutes player
    aliases: [mute,unmute,uumute,ununmute,uunmute]
  lockdown:
    description: Lockdown the Server
    usage: /<command> <on/off/status>
  editban:
    description: Edit a ban
    usage: /<command> <list/load/id/save/view/reason/time/cancel/help>
    aliases: [eb,eban]
  uhelp:
    description: Shows Help
    usage: /<command>
  uversion:
    description: Shows current Ultrabans Version
    usage: /<command>
    aliases: [uv,uver]
