#Change to MySQL for mysql support#
#Change to SQLite for sqlite support#
Database: SQLite
mysql-database: 'jdbc:mysql://localhost:3306/minecraft'
mysql-user: 'root'
mysql-password: 'root'
#Change these if you want to load or create different databases#
#First load will create these databases#
mysql-table: banlist
mysql-table-ip: banlistip
#SQLite Information#
sqlite-dbname: banlist
#parameters#
auto-complete: true
#delete dat on ban#
CleanOnBan: true
#kick on max ping#
KickMaxPing: true
MaxPing: 200
#Max allowable fine#
#If Zero then no max will be placed#
maxFineAmt: 0
#Disable command usage on muted#
muteVanilla: true
#Max Warnings#
enableMaxWarn: false#
maxWarnings: 5
#ban,kick,ipban,perma,tempban,tempipban#
maxWarnResult: ban
#Used with Temporary actions#
maxWarnResulttime:
  amt: 5
  #sec,min,hour,day,week,month#
  mode: day
#Default labels#
defAdminName: 'server'
defReason: 'not sure'
#change to true or false to enable lockdown#
#also can be done ingame /lockdown#
lockdown: false
#Enabling dupePolicy will disallow duplicate IP connections#
dupePolicy: false
enableLoginDupeCheck: true
serverSync:
  #This will set the server to sync the database if multiple servers are in place.#
  enable: false
  #Timing is in Long format Example:#
  #1 Hour = 60 Seconds * 60 Minutes * 20 ServerTickRatePerSec = 72000L
  timing: 72000L

#Chat#
Chat:
  #Checks Chat Messages for a valid IP address#
  #If its not valid, trust me they can't connect to it#
  IPCheck:
    Enable: true
    #Wildcards %scramble% will scramble the ip and %replace% will show your ip instead#
    #If no wildcards are present the message entered will replace the ip#
    #leave blank to erase#
    Blocking: '{Block}'
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: warn
    Silent: false

  #This will allow you to filter out messages containing any words that you define#
  SwearCensor:
    Enable: true
    #Use your imagination these are not for me to decide#
    Words: 'test testing tests'
    #Wildcards %scramble% will scramble the ip and %replace% will show your ip instead#
    #If no wildcards are present the message entered will replace the ip#
    #leave blank to erase#
    Blocking: '{Block}'
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: warn
    Silent: false

  #Checks if the message is duplicate and disables it#
  SpamCheck:
    Enable: true
    #The amount of messages to give a result#
    Counter: 10
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: kick
    Silent: false


#Messages#
messages:
  banMsgFailed: '&4%victim% &7is already banned!'
  unbanMsg: '&7Successfully unbanned &4%victim%&7!'
  unbanMsgBroadcast: '&4%victim% &7was unbanned by &3%admin%&7!'
  unbanMsgFailed: '&4%victim% &7is already unbanned!'
  kickAllMsg: '%admin% kicked everyone. Reason: %reason%!'
  kickMsgVictim: 'You have been kicked by %admin%. Reason: %reason%!'
  kickMsgBroadcast: '&4%victim% &7was kicked by &3%admin%&7. Reason: &4%reason%!'
  kickMsgFailed: '&7Kick failed: &7%victim% &7isn''t online.'
  banMsgVictim: 'You have been banned by %admin%. Reason: %reason%!'
  banMsgBroadcast: '&4%victim% &7was banned by &3%admin%&7. Reason: &4%reason%!'
  permbanMsgVictim: 'You have been permabanned by %admin%. Reason: %reason%!'
  permbanMsgBroadcast: '&4%victim% &7has been permabanned by &3%admin%&7. Reason: &4%reason%!'
  tempbanMsgVictim: 'You have been temp. banned by %admin%. Reason: %reason%!'
  tempbanMsgBroadcast: '&4%victim% &7was temp. banned by &3%admin%&7. Reason: &4%reason%!'
  LoginTempban: '&7You are banned until &4%time%&7! Reason: &4%reason%!'
  LoginBan: '%admin% banned you from this server! Reason: %reason%!'
  LoginIPBan: 'Your IP is banned!'
  fineMsgVictim: 'You have been fined by %admin% in the amount of %amt%!'
  fineMsgBroadcast: '&4%victim% &7was fined by &3%admin%&7 in the amount of &4%amt%!'
  emptyMsgVictim: '&3%admin% has cleared your inventory!'
  emptyMsgBroadcast: '&3%admin% has cleared the inventory of &4%victim%!'
  starveMsgVictim: '&7You are now starving!'
  starveMsgBroadcast: '&4%victim% is now starving!'
  fspawnMsgVictim: '&7You have been sent to spawn!'
  fspawnMsgBroadcast: '&4%victim% &7is now at spawn!'
  jailMsgVictim: '&7You have been jailed by &3%admin%&7. Reason: &4%reason%!'
  jailMsgRelease: '&4%victim% &7was released from jail by &3%admin%&7!'
  jailMsgBroadcast: '&4%victim% &7was jailed by &3%admin%&7. Reason: &4%reason%!'
  warnMsgVictim: '&7You have been warned by &3%admin%&7. Reason: &4%reason%!'
  warnMsgBroadcast: '&4%victim% &7was warned by &3%admin%&7. Reason: &4%reason%!'
  lockMsgLogin: 'Server is under a lockdown, Try again later! Sorry.'
  DupeIPKick: 'Duplicate IP addresses disabled.'
  jailCmdMsg: 'You cannot use commands while jailed!'
  jailChatMsg: 'Your cry falls on deaf ears.'
  jailPlaceMsg: 'You cannot place blocks while you are jailed!'
  jailBreakMsg: 'You cannot break blocks while you are jailed!'
  tempjailMsgVictim: 'You have been temp. jailed by %admin%. Reason: %reason%!'
  tempjailMsgBroadcast: '&4%victim% &7was temp. jailed by &3%admin%&7. Reason: &4%reason%!'
  tempipbanMsgVictim: 'You have been temp. ipbanned by %admin%. Reason: %reason%!'
  tempipbanMsgBroadcast: '&4%victim% &7was temp. ipbanned by &3%admin%&7. Reason: &4%reason%!'
  muteChatMsg: 'You have been muted!'
  muteMsg: 'You have muted %victim%.'
  unmuteMsgVictim: 'You have been unmuted.'
  unmuteMsg: 'You have unmuted %victim%.'
#Do Not Change Values Below#
jail:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
