#Change to MySQL for mysql support#
#Change to SQLite for sqlite support#
Database: SQLite
#MySQL Information#
MySQL:
  Address: 'jdbc:mysql://localhost:3306/minecraft'
  User: 'root'
  Password: 'root'
  Table: 'banlist'
  IPTable: 'banlistip'
#SQLite Information#
SQLite:
  Filename: 'banlist'
#delete dat on ban#
CleanOnBan: true
#Max Warnings#
MaxWarning:
  Enable: false#
  Amt: 5
  #ban,kick,ipban,perma,tempban,tempipban#
  Result: ban
  Silent: true
  Message: 'Max Warnings'
  #Used with Temporary actions#
  Temp:
    Amt: 5
  #sec,min,hour,day,week,month#
    Mode: day
#Default labels#
Label:
  Console: 'Server'
  Reason: 'Unsure'
#change to true or false to enable lockdown#
#also can be done ingame /lockdown#
Lockdown: false
Login:
#Check for duplicates on Login#
  DupeCheck:
    Enable: true
#Check ping on Login#
  PingCheck:
    Enable: true
    MaxPing: 200
#This will set the server to sync the database if multiple servers are in place.#
Sync:
  Enabled: false
  #Timing is in Long format Example:#
  #1 Hour = 60 Seconds * 60 Minutes * 20 ServerTickRatePerSec = 72000L
  Timing: 72000L
#Enable Ultrabans Live Server#
Live:
  Enabled: false
  Port: 9981
#Auto Updater#
AutoUpdater:
  Enabled: true
#Error / Usage Tracking#
GoogleAnalytics:
  Enable: true
#Chat#
Chat:
  #Checks Chat Messages for a valid IP address#
  #If its not valid, trust me they can't connect to it#
  IPCheck:
    Enable: true
    #Wildcards %scramble% will scramble the ip and %replace% will show your ip instead#
    #If no wildcards are present the message entered will replace the ip#
    #leave blank to erase#
    Blocking: '{Block}'
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: warn
    Silent: false
    Reason: 'Advertising'
  #This will allow you to filter out messages containing any words that you define#
  SwearCensor:
    Enable: true
    #Use your imagination these are not for me to decide#
    Words: 'test testing tests'
    #Wildcards %scramble% will scramble the ip and %replace% will show your ip instead#
    #If no wildcards are present the message entered will replace the ip#
    #leave blank to erase#
    Blocking: '{Block}'
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: warn
    Silent: false
    Reason: 'Language'
  #Checks if the message is duplicate and disables it#
  SpamCheck:
    Enable: true
    #The amount of messages to give a result#
    Counter: 10
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: kick
    Silent: false
    Reason: 'Spam'
Muted:
  Vannila: true
  #When Vanilla: true allowed commands.#
  AllowedCommands:
  - '/login'
  - '/register'
#Jail Configuration#
Jail:
  Mute: true
  Vanilla: true
  #When Vanilla: true allowed commands.#
  AllowedCommands:
  - '/login'
  - '/register'
Messages:
  Ban:
    MsgToVictim: 'You have been banned by %admin%. Reason: %reason%!'
    MsgToBroadcast: '%victim% was banned by %admin%. Reason: %reason%!'
    Failed: '%victim% is already in banned.'
    Denied: 'Your ban attempt has been denied!'
    Emo: 'You cannot ban yourself!'   
    Login: '%admin% banned you from this server! Reason: %reason%!'
  CheckBan:
    Header: 'Found %amt% records for %victim%.'
    None: 'No records found for %victim%.'
  Clean:
    Complete: 'Deleted %amt% player.dat files.'
  DupeIP:
    Failed: 'Unable to view ip for %victim% !'
    Header: 'Scanning Current IP of %victim%: %ip% !'
    Completed: 'Scanning Complete!'
  Empty:
    MsgToVictim: '%admin% has cleared your inventory!'
    MsgToSender: '%admin% has cleared the inventory of %victim%!'
    Online: '%victim% must be online.'
  Export:
    Failed: 'Could not export ban lists.'
    Completed: 'Exported banlists.'
  History:
    Header: 'Ultrabans Listing %amt% Records.'
    Failed: 'Unable to find any bans.'
  Import:
    Loading: 'Be patient. Loading...'
    Failed: 'Could not import ban list.'
    Completed: 'System imported the banlist to the database.'
  InvOf:
    Failed: 'Unable to find player.'
    Console: 'This command must be executed by a player.'
  IPBan:
    MsgToVictim: 'You have been ipbanned by %admin%. Reason: %reason%!'
    MsgToBroadcast: '%victim% was ipbanned by %admin%. Reason: %reason%!'
    IPNotFound: 'IP address not found. Processed as a normal ban for %victim%!' 
    Failed: '%victim% is already in banned.'
    Denied: 'Your ipban attempt has been denied!'
    Emo: 'You cannot ipban yourself!'
    Login: 'Your IP is banned!'   
  Jail:
    MsgToVictim: 'You have been jailed by %admin%. Reason: %reason%!'
    MsgToBroadcast: '%victim% was jailed by %admin%. Reason: %reason%!'
    SetJail: 'Jail has been set!'
    SetRelease: 'Release has been set!'
    Failed: '%victim% is already in jail.'
    Online: '%victim% must be online to be jailed.'
    Denied: 'Your jail attempt has been denied!'
    Emo: 'You cannot jail yourself!'
    PlaceMsg: 'You cannot place blocks while you are jailed!'
    BreakMsg: 'You cannot break blocks while you are jailed!'
  Kick:
    MsgToAll: 'Everyone has been kicked by %admin%. Reason: %reason%'
    MsgToVictim: 'You have been kicked by %admin%. Reason: %reason%!'
    MsgToBroadcast: '%victim% was kicked by %admin%. Reason: %reason%!'
    Online: '%victim% must be online.'
    Denied: 'Your kick has been denied!'
    Emo: 'You cannot kick yourself!'  
  Lockdown:
    Start: 'Lockdown initiated. PlayerLogin disabled.'
    End: 'Lockdown ended. PlayerLogin reenabled.'
    Status: 'Lockdown is disabled.'
    LoginMsg: 'Server is under a lockdown, Try again later! Sorry.'
  Mute:
    MuteMsgToSender: 'You have muted %victim%.'
    MuteMsgToVictim: 'You have been muted!'
    UnmuteMsgToSender: 'You have unmuted %victim%.'
    UnmuteMsgToVictim: 'You have been unmuted.'
    Denied: 'Your mute has been denied!'
    Emo: 'You cannot mute yourself!'
    Chat: 'Your cry falls on deaf ears.'   
  Pardon:
    Msg: '%victim% was released from jail by %admin%!'
  PermaBan:
    MsgToVictim: 'You have been permabanned by %admin%. Reason: %reason%!'
    MsgToBroadcast: '%victim% was permabanned by %admin%. Reason: %reason%!'
    Failed: '%victim% is already banned.'
    Online: '%victim% must be online.'
    Denied: 'Your permaban has been denied!'
    Emo: 'You cannot permaban yourself!'    
  Spawn:
    MsgToVictim: 'You have been sent to spawn!'
    MsgToSender: '%victim% is now at spawn!'
    Failed: '%victim% is not online.'
  Starve:
    MsgToVictim: 'You are now starving!'
    MsgToSender: '%victim% is now starving!'
    Failed: '%victim% is not online.'
    Denied: 'Your starve attempt has been denied!'
    Emo: 'You cannot starve yourself!'
  TempBan:
    MsgToVictim: 'You have been tempbanned by %admin% for %amt% %mode%s. Reason: %reason%!'
    MsgToBroadcast: '%victim% was tempbanned by %admin% for %amt% %mode%s. Reason: %reason%!'
    Failed: '%victim% is already tempbanned!'
    Denied: 'Your tempban has been denied!'
    Emo: 'You cannot tempban yourself!'
    Login: 'You have been tempbanned by %admin% for %time%. Reason: %reason%!'
  TempIpBan:
    MsgToVictim: 'You have been tempipbanned by %admin% for %amt% %mode%s. Reason: %reason%!'
    MsgToBroadcast: '%victim% was tempipbanned by %admin% for %amt% %mode%s. Reason: %reason%!'
    Failed: '%victim% is already tempipbanned!'
    Denied: 'Your tempipban has been denied!'
    Emo: 'You cannot tempipban yourself!'
    IPNotFound: 'IP address not found. Processed as a normal tempban for %victim%!'  
  TempJail:
    MsgToVictim: 'You have been tempjailed by %admin% for %amt% %mode%s. Reason: %reason%!'
    MsgToBroadcast: '%victim% was tempjailed by %admin% for %amt% %mode%s. Reason: %reason%!'
    Failed: '%victim% is already jailed!'
    Denied: 'Your tempjail has been denied!'
    Emo: 'You cannot tempjail yourself!'
  Unban:
    MsgToBroadcast: '%victim% was unbanned by %admin%!'
    PermaBanned: 'Unable to unban, %victim% was Permabanned.'
    Failed: '%victim% is already unbanned!'
  Warn:
    MsgToVictim: 'You have been warned by %admin%. Reason: %reason%'
    MsgToBroadcast: '%victim% was warned by %admin%. Reason: %reason%'
    Denied: 'Your warning has been denied!'
    Emo: 'You cannot warn yourself!'
  MaxWarn:
    MsgToBroadcast: '%cmd% performed by Ultrabans on %victim%. Reason: Reached Max Warnings'
  Permission: 'You do not have the required permissions.'
#Do Not Change Values Below#
jail:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
