#Change to MySQL for mysql support#
#Change to SQLite for sqlite support#
Database: SQLite
#MySQL Information#
MySQL:
  Address: 'jdbc:mysql://localhost:3306/minecraft'
  User: 'root'
  Password: 'root'
  Table: banlist
  IPTable: banlistip
#SQLite Information#
SQLite:
  Filename: banlist
#delete dat on ban#
CleanOnBan: true
#kick on max ping#
KickMaxPing: true
MaxPing: 200
#Disable command usage on muted#
muteVanilla: true
#Max Warnings#
MaxWarning:
  Enable: false#
  Amt: 5
  #ban,kick,ipban,perma,tempban,tempipban#
  Result: ban
  Silent: true
  Message: 'Max Warnings'
  #Used with Temporary actions#
  Temp:
    Amt: 5
  #sec,min,hour,day,week,month#
    Mode: day
#Default labels#
Label:
  Console: 'Server'
  Reason: 'Unsure'
#change to true or false to enable lockdown#
#also can be done ingame /lockdown#
lockdown: false
#Enabling dupePolicy will disallow duplicate IP connections#
dupePolicy: false
enableLoginDupeCheck: true
#This will set the server to sync the database if multiple servers are in place.#
Sync:
  Enabled: false
  #Timing is in Long format Example:#
  #1 Hour = 60 Seconds * 60 Minutes * 20 ServerTickRatePerSec = 72000L
  Timing: 72000L
#Enable Live Server#
Live:
  Enabled: false
  Port: 9981
#Auto Updater#
AutoUpdater:
  Enabled: true
#Error / Usage Tracking#
GoogleAnalytics:
  Enable: true
#Chat#
Chat:
  #Checks Chat Messages for a valid IP address#
  #If its not valid, trust me they can't connect to it#
  IPCheck:
    Enable: true
    #Wildcards %scramble% will scramble the ip and %replace% will show your ip instead#
    #If no wildcards are present the message entered will replace the ip#
    #leave blank to erase#
    Blocking: '{Block}'
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: warn
    Silent: false

  #This will allow you to filter out messages containing any words that you define#
  SwearCensor:
    Enable: true
    #Use your imagination these are not for me to decide#
    Words: 'test testing tests'
    #Wildcards %scramble% will scramble the ip and %replace% will show your ip instead#
    #If no wildcards are present the message entered will replace the ip#
    #leave blank to erase#
    Blocking: '{Block}'
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: warn
    Silent: false

  #Checks if the message is duplicate and disables it#
  SpamCheck:
    Enable: true
    #The amount of messages to give a result#
    Counter: 10
    #kick,jail,warn,ban,ipban, leave blank for no action#
    Result: kick
    Silent: false


#Messages#
messages:
  banMsgFailed: '&4%victim% &7is already banned!'
  unbanMsg: '&7Successfully unbanned &4%victim%&7!'
  unbanMsgBroadcast: '&4%victim% &7was unbanned by &3%admin%&7!'
  unbanMsgFailed: '&4%victim% &7is already unbanned!'
  kickAllMsg: '%admin% kicked everyone. Reason: %reason%!'
  kickMsgVictim: 'You have been kicked by %admin%. Reason: %reason%!'
  kickMsgBroadcast: '&4%victim% &7was kicked by &3%admin%&7. Reason: &4%reason%!'
  kickMsgFailed: '&7Kick failed: &7%victim% &7isn''t online.'
  banMsgVictim: 'You have been banned by %admin%. Reason: %reason%!'
  banMsgBroadcast: '&4%victim% &7was banned by &3%admin%&7. Reason: &4%reason%!'
  permbanMsgVictim: 'You have been permabanned by %admin%. Reason: %reason%!'
  permbanMsgBroadcast: '&4%victim% &7has been permabanned by &3%admin%&7. Reason: &4%reason%!'
  tempbanMsgVictim: 'You have been temp. banned by %admin%. Reason: %reason%!'
  tempbanMsgBroadcast: '&4%victim% &7was temp. banned by &3%admin%&7. Reason: &4%reason%!'
  LoginTempban: '&7You are banned until &4%time%&7! Reason: &4%reason%!'
  LoginBan: '%admin% banned you from this server! Reason: %reason%!'
  LoginIPBan: 'Your IP is banned!'
  emptyMsgVictim: '&3%admin% has cleared your inventory!'
  emptyMsgBroadcast: '&3%admin% has cleared the inventory of &4%victim%!'
  starveMsgVictim: '&7You are now starving!'
  starveMsgBroadcast: '&4%victim% is now starving!'
  fspawnMsgVictim: '&7You have been sent to spawn!'
  fspawnMsgBroadcast: '&4%victim% &7is now at spawn!'
  jailMsgVictim: '&7You have been jailed by &3%admin%&7. Reason: &4%reason%!'
  jailMsgRelease: '&4%victim% &7was released from jail by &3%admin%&7!'
  jailMsgBroadcast: '&4%victim% &7was jailed by &3%admin%&7. Reason: &4%reason%!'
  lockMsgLogin: 'Server is under a lockdown, Try again later! Sorry.'
  DupeIPKick: 'Duplicate IP addresses disabled.'
  jailCmdMsg: 'You cannot use commands while jailed!'
  jailChatMsg: 'Your cry falls on deaf ears.'
  jailPlaceMsg: 'You cannot place blocks while you are jailed!'
  jailBreakMsg: 'You cannot break blocks while you are jailed!'
  tempipbanMsgVictim: 'You have been temp. ipbanned by %admin%. Reason: %reason%!'
  tempipbanMsgBroadcast: '&4%victim% &7was temp. ipbanned by &3%admin%&7. Reason: &4%reason%!'
  muteChatMsg: 'You have been muted!'
  muteMsg: 'You have muted %victim%.'
  unmuteMsgVictim: 'You have been unmuted.'
  unmuteMsg: 'You have unmuted %victim%.'
Messages:
  TempBan:
    MsgToVictim: 'You have been tempbanned by %admin% for %amt% %mode%s. Reason: %reason%!'
    MsgToBroadcast: '%victim% was tempbanned by %admin% for %amt% %mode%s. Reason: %reason%!'
    Failed: '%victim% is already tempbanned!'
    Denied: 'Your tempban has been denied!'
    Emo: 'You cannot tempban yourself!'
  TempIpBan:
    MsgToVictim: 'You have been tempipbanned by %admin% for %amt% %mode%s. Reason: %reason%!'
    MsgToBroadcast: '%victim% was tempipbanned by %admin% for %amt% %mode%s. Reason: %reason%!'
    Failed: '%victim% is already tempipbanned!'
    Denied: 'Your tempipban has been denied!'
    Emo: 'You cannot tempipban yourself!'
    IPNotFound: 'IP address not found. Processed as a normal tempban for %victim%!'  
  TempJail:
    MsgToVictim: 'You have been tempjailed by %admin% for %amt% %mode%s. Reason: %reason%!'
    MsgToBroadcast: '%victim% was tempjailed by %admin% for %amt% %mode%s. Reason: %reason%!'
    Failed: '%victim% is already jailed!'
    Denied: 'Your tempjail has been denied!'
    Emo: 'You cannot tempjail yourself!'
  Unban:
    MsgToBroadcast: '%victim% was unbanned by %admin%!'
    PermaBanned: 'Unable to unban, %Victim% was Permabanned.'
    Failed: '%victim% is already unbanned!'
  Warn:
    MsgToVictim: 'You have been warned by %admin%. Reason: %reason%'
    MsgToBroadcast: '%victim% was warned by %admin%. Reason: %reason%'
    Denied: 'Your warning has been denied!'
    Emo: 'You cannot warn yourself!'
  MaxWarn:
    MsgToBroadcast: '%cmd% performed by Ultrabans on %victim%. Reason: Reached Max Warnings'
  Permission: 'You do not have the required permissions.'
#Do Not Change Values Below#
jail:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
